# Generated by Django 2.2 on 2019-04-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_analysis2'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='analysis_results',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='analysis2',
            name='analysis_results',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
